platform :ios, '9.0'
use_frameworks!

target 'RedditApp' do
    pod 'Alamofire'
    pod 'Gloss'
    pod 'SQLite.swift', '~> 0.11.2'
    pod 'KeychainSwift'
    pod 'FBSDKCoreKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKLoginKit'
    pod 'SwiftGifOrigin'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end